## 7.1 处理缺失值
### 7.1.1 过滤缺失值

In [1]:
#dropna返回所有非空数据集及其索引
import numpy as np
import pandas as pd
from numpy import nan as NA

In [4]:
#dropna返回所有非空数据集及其索引
data =pd.Series([1,NA,3.5,NA,7])
print(data.dropna())
#上面得例子和下面得代码等价
print(data[data.notnull()])

0    1.0
2    3.5
4    7.0
dtype: float64
0    1.0
2    3.5
4    7.0
dtype: float64


In [10]:
#dropna删除包含缺失值得行
#how="all"参数删除均为nan的行  data.dropna(how="all")
#想要删除列时，传入参数axis=1即可


#thresh参数表示保留一定数量的观察值的行
df=pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1]=NA   #iloc表示到第几行，loc表示到整数
df.iloc[:2,2]=NA
print(df)
print(df.dropna(thresh=2))

          0         1         2
0 -1.636595       NaN       NaN
1 -1.123301       NaN       NaN
2 -0.554647       NaN  1.355724
3  0.470459       NaN -2.108274
4  1.631401  1.595943 -0.107675
5  0.677020 -1.406489 -1.265448
6  0.104145  1.093956  1.207495
          0         1         2
2 -0.554647       NaN  1.355724
3  0.470459       NaN -2.108274
4  1.631401  1.595943 -0.107675
5  0.677020 -1.406489 -1.265448
6  0.104145  1.093956  1.207495


### 7.1.2 补全缺失值

In [11]:
#主要用fillna方法补全，可以使用常数来代替
df.fillna(0)

0         1         2
0 -1.636595  0.000000  0.000000
1 -1.123301  0.000000  0.000000
2 -0.554647  0.000000  1.355724
3  0.470459  0.000000 -2.108274
4  1.631401  1.595943 -0.107675
5  0.677020 -1.406489 -1.265448
6  0.104145  1.093956  1.207495

In [12]:
df.fillna({1:0.5,2:0}) #不同的列设置不同的值

0         1         2
0 -1.636595  0.500000  0.000000
1 -1.123301  0.500000  0.000000
2 -0.554647  0.500000  1.355724
3  0.470459  0.500000 -2.108274
4  1.631401  1.595943 -0.107675
5  0.677020 -1.406489 -1.265448
6  0.104145  1.093956  1.207495

In [13]:
#填充Series平均值
data=pd.Series([1.,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 数据转换
### 7.2.1 删除重复值

In [14]:
data=pd.DataFrame({'k1':['one','two']*3+['two'],
                  'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [15]:
#duplicated判断是否存在重复的行
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [17]:
data.drop_duplicates()#返回不重复的行

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [18]:
data['v1']=range(7)
data.drop_duplicates(['k1'])  #指定列取唯一值

k1  k2  v1
0  one   1   0
1  two   1   1

In [19]:
data.drop_duplicates(['k1','k2'],keep='last')#保持唯一性时，保存最后一个匹配到的值

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 7.2.2 使用函数或映射进行数据转换

In [20]:
data=pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],
                  'ounces':[4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [21]:
#添加一列肉的类型
meat_to_animal={
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}
lowercased=data['food'].str.lower()#将字母全都变成小写
data['animal']=lowercased.map(meat_to_animal)  #用map进行匹配
data


food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### 7.2.3 替代值

In [22]:
data=pd.Series([1.,-999.,2.,-999.,-1000.,3.])
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [23]:
#一次替代多个值
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [25]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [26]:
#参数也可以通过字典传递
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 7.2.4 重命名轴索引

In [31]:
data=pd.DataFrame(np.arange(12).reshape((3,4)),
                 index=['Ohio','Colorado','New York'],
                 columns=['one','two','three','four'])
#与Series类似，轴索引也有一个man方法
transform=lambda x: x[:4].upper()
data.index=data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [32]:
#改名
data.rename(index={'OHIO':'INDIANA'},
           columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### 7.2.5 离散化和分箱

In [33]:
#将年龄放入离散的年龄框
ages=[20,22,25,27,21,23,37,31,61,45,41,32]
bins=[18,25,35,60,100]
cats=pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [35]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [36]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [38]:
pd.value_counts(cats)#统计箱中的数量

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [39]:
pd.cut(ages,bins,right=False) #改变箱子在哪一边封闭

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [42]:
#传入标签，定义箱子的名字
group_names=['Youth','YoungAdult','MiddleAged','Senior']
pd.cut(ages,bins,labels=group_names)


['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [43]:
#均匀分布的数据被切成四份
data=np.random.rand(20)
pd.cut(data,4,precision=2)#十进制精确显示到2位

[(0.027, 0.27], (0.51, 0.75], (0.27, 0.51], (0.027, 0.27], (0.027, 0.27], ..., (0.75, 0.99], (0.75, 0.99], (0.27, 0.51], (0.027, 0.27], (0.27, 0.51]]
Length: 20
Categories (4, interval[float64]): [(0.027, 0.27] < (0.27, 0.51] < (0.51, 0.75] < (0.75, 0.99]]

In [45]:
pd.value_counts(pd.cut(data,4,precision=2))

(0.027, 0.27]    9
(0.75, 0.99]     4
(0.27, 0.51]     4
(0.51, 0.75]     3
dtype: int64

In [46]:
#qcut按照样本数分为四份
data=np.random.randn(1000) #正态分布
cats=pd.qcut(data,4) #切成四份
cats

[(-0.617, 0.0461], (-3.093, -0.617], (-3.093, -0.617], (0.729, 2.952], (0.0461, 0.729], ..., (0.729, 2.952], (-0.617, 0.0461], (0.729, 2.952], (-3.093, -0.617], (-3.093, -0.617]]
Length: 1000
Categories (4, interval[float64]): [(-3.093, -0.617] < (-0.617, 0.0461] < (0.0461, 0.729] < (0.729, 2.952]]

In [47]:
pd.value_counts(cats)

(0.729, 2.952]      250
(0.0461, 0.729]     250
(-0.617, 0.0461]    250
(-3.093, -0.617]    250
dtype: int64

### 7.2.6 检测或过滤异常值

In [48]:
data=pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.020640    -0.009536    -0.010298    -0.061508
std       0.983621     0.999719     1.028750     0.984634
min      -3.177316    -2.959062    -3.312067    -2.992985
25%      -0.611611    -0.656647    -0.696017    -0.734688
50%       0.021737    -0.031275    -0.010333    -0.090252
75%       0.646336     0.638618     0.666295     0.650880
max       3.085637     3.504316     2.990755     3.052517

In [49]:
#选出一列中绝对值大于三的值
col=data[2]
col[np.abs(col)>3]

285   -3.046915
664   -3.090184
698   -3.312067
814   -3.035446
Name: 2, dtype: float64

In [50]:
#选出所有值大于3或小于-3的行，使用any方法
data[(np.abs(data)>3).any(1)]

0         1         2         3
237 -0.316663 -1.079598 -0.764964  3.052517
285 -0.839591 -1.040896 -3.046915  1.428123
404  1.604998  3.504316  0.370888  0.898374
502 -3.177316 -1.200290  0.455491  0.873027
584  3.058175  0.285632  0.118187 -0.171360
610 -3.009938 -1.982418 -0.301124  0.845342
634  3.085637 -0.409272  0.112238  0.201730
664 -0.446669  0.234211 -3.090184  1.294225
698 -0.385264  0.208407 -3.312067 -0.444818
814  0.744475  1.766868 -3.035446  0.638925
833 -1.147331  3.127535  0.275517 -0.030354

In [51]:
#对-3到3之间的数值设置限制
data[np.abs(data)>3]=np.sign(data)*3 
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.020684    -0.010168    -0.009813    -0.061560
std       0.982587     0.997677     1.027286     0.984469
min      -3.000000    -2.959062    -3.000000    -2.992985
25%      -0.611611    -0.656647    -0.696017    -0.734688
50%       0.021737    -0.031275    -0.010333    -0.090252
75%       0.646336     0.638618     0.666295     0.650880
max       3.000000     3.000000     2.990755     3.000000

In [52]:
#观察正负
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0 -1.0
1 -1.0 -1.0  1.0 -1.0
2 -1.0  1.0  1.0  1.0
3  1.0 -1.0  1.0  1.0
4  1.0 -1.0 -1.0 -1.0

### 7.2.7 置换和随机抽样

In [54]:
df=pd.DataFrame(np.arange(5*4).reshape((5,4)))
sampler=np.random.permutation(5)#产生一个表示新顺序的整数数组
sampler

array([1, 4, 2, 3, 0])

In [55]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [56]:
df.take(sampler)#改变行序

0   1   2   3
1   4   5   6   7
4  16  17  18  19
2   8   9  10  11
3  12  13  14  15
0   0   1   2   3

In [57]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7

In [60]:
#生成有代替值得样本（允许有重复选择）
choices=pd.Series([5,7,-1,6,4])
draws=choices.sample(n=10,replace=True)
draws

1    7
0    5
2   -1
3    6
1    7
0    5
3    6
2   -1
2   -1
1    7
dtype: int64

### 7.2.8 计算指标/虚拟变量


In [63]:
df=pd.DataFrame({'key':['b','b','a','c','a','b'],
                'data1': range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [65]:
#某种情况下可能想要加入前缀，并与其他数据合并
dummies=pd.get_dummies(df['key'],prefix='key')
df_with_dummy=df[['data1']].join(dummies)
df_with_dummy#加了一列索引

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [66]:
#将get_dummies与cut等离散化函数结合使用是统计应用得一个有用方法
np.random.seed(12345)
values=np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [67]:
bins=[0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [70]:
np.random.seed(12345)
values=np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

### 7.3.1 字符串对象方法

In [71]:
#split拆解字符串
val='a,b,  guido'
val.split(',')

['a', 'b', '  guido']

In [73]:
#以下两个方法可以产生同样的效果
f,s,t=val.split(',')
print(f+'::'+s+'::'+t)
print('::'.join(val.split(',')))

a::b::  guido
a::b::  guido


In [75]:
val.count(',')

2

In [76]:
val.replace(',','::')

'a::b::  guido'

### 7.3.2 正则表达式

In [77]:
import re
text="foo    bar\t baz  \tqux"
re.split('\s+',text)
#当调用re.split，正则表达式首先会被编译，然后正则表达式的split方法再传入文本上被调用。可以使用re.compile自行编译，形成一个可复用的正则表达式对象

['foo', 'bar', 'baz', 'qux']

In [78]:
regex=re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

#### findall: 返回的是字符串中所有的匹配项
#### search: 返回的仅仅是第一项
#### match: 它只在字符串的起始位置进行匹配

In [80]:
text="""
Dave dave@goole.com
Steve steve@gmail.com
Rob rob@gmain.com
Ryan ryan@yahoo.com"""
pattern=r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex=re.compile(pattern,flags=re.IGNORECASE)#不区分大小写
#生成一个电子邮件列表
regex.findall(text)

['dave@goole.com', 'steve@gmail.com', 'rob@gmain.com', 'ryan@yahoo.com']

In [85]:
m=regex.search(text)#返回第一个的存储位置
m

<re.Match object; span=(6, 20), match='dave@goole.com'>

In [86]:
text[m.start():m.end()]

'dave@goole.com'

In [87]:
print(regex.match(text))

None


In [89]:
#想要将每个地址分为三个部分，将每个部分用括号括起来
pattern=r'([A-Z0-9._%+-]+)+@([A-Z0-9.-]+)+\.([A-Z]{2,4})'
regex=re.compile(pattern,flags=re.IGNORECASE)
regex.findall(text)

[('dave', 'goole', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmain', 'com'),
 ('ryan', 'yahoo', 'com')]

In [90]:
#分组访问
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3',text))


Dave Username: dave, Domain: goole, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmain, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com
